[project]
name = "forecasting"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "doubleml>=0.11.4",
    "econml>=0.17.0",
    "holidays>=0.82",
    "ipykernel>=7.0.1",
    "kagglehub>=1.0.2",
    "kaleido==0.2.1",
    "lightgbm>=4.6.0",
    "matplotlib>=3.10.7",
    "mlforecast>=1.0.2",
    "nbformat>=5.10.4",
    "networkx>=3.4.2",
    "pandas>=2.3.3",
    "plotly>=6.3.1",
    "seaborn>=0.13.2",
    "statsforecast>=2.0.2",
    "tinyshift[all]>=1.5.2",
]
